### ISSUE TITLE
ERROR [InputLauncher] The [org.graylog2.plugin.httpmonitor.HttpMonitorInput] input with ID <571acf77e4b0854adf462f52> misfired. Reason: scheme.

### ISSUE THREAD

**Issue by msteelepmp** [sivasamyk/graylog2-plugin-input-httpmonitor#5]
Getting an NPE when trying to launch this the first time. I've tried a couple of different web sites to see if it's a configuration issue on my side. But no luck. any ideas?

Using graylog-web-interface v1.3.4 (0d67a80) (Oracle Corporation 1.8.0_77 / Linux 2.6.32-573.22.1.el6.x86_64)

`ERROR [InputLauncher] The [org.graylog2.plugin.httpmonitor.HttpMonitorInput] input with ID <571acf77e4b0854adf462f52> misfired. Reason: scheme.
org.graylog2.plugin.inputs.MisfireException: java.lang.NullPointerException: scheme
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:163)
        at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: scheme
        at com.ning.http.client.uri.Uri.<init>(Uri.java:56)
        at com.ning.http.client.uri.Uri.create(Uri.java:32)
        at com.ning.http.client.uri.Uri.create(Uri.java:25)
        at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:307)
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.setUrl(AsyncHttpClient.java:308)
        at com.ning.http.client.AsyncHttpClient.requestBuilder(AsyncHttpClient.java:596)
        at com.ning.http.client.AsyncHttpClient.prepareGet(AsyncHttpClient.java:402)
        at org.graylog2.plugin.httpmonitor.HttpMonitorTransport$MonitorTask.buildRequest(HttpMonitorTransport.java:285)
        at org.graylog2.plugin.httpmonitor.HttpMonitorTransport$MonitorTask.<init>(HttpMonitorTransport.java:174)
        at org.graylog2.plugin.httpmonitor.HttpMonitorTransport.startMonitoring(HttpMonitorTransport.java:151)
        at org.graylog2.plugin.httpmonitor.HttpMonitorTransport.launch(HttpMonitorTransport.java:132)
        at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:160)
        ... 7 more
2016-04-23T01:27:19.187Z INFO  [InputStateListener] Input [HTTP Monitor/571acf77e4b0854adf462f52] is now FAILED`

**Comment by sivasamyk** [comment]
I assume your URL to monitor is something like `http://www.google.com` and not `www.google.com`. You need to specify the scheme (http or https)

**Comment by msteelepmp** [comment]
Thanks...silly oversight on my part.
