### ISSUE TITLE
HttpMonitorTransport - Exception while executing request

### ISSUE THREAD

**Issue by elgersonloco** [sivasamyk/graylog2-plugin-input-httpmonitor#7]
2016-08-10 18:00:44,949 DEBUG: org.graylog2.plugin.httpmonitor.HttpMonitorTransport - Exception while executing request for URL https://midominio.com:8081/v1
java.util.concurrent.ExecutionException: java.net.ConnectException: https://midominio.com:8081
    at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231) ~[?:?]
    at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:135) ~[?:?]
    at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[?:?]
    at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:104) ~[?:?]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[graylog.jar:?]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[graylog.jar:?]
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[graylog.jar:?]
    at org.jboss.netty.handler.ssl.SslHandler.channelDisconnected(SslHandler.java:575) ~[graylog.jar:?]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102) ~[graylog.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[graylog.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[graylog.jar:?]
    at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[graylog.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[graylog.jar:?]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[graylog.jar:?]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[graylog.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.net.ConnectException: https://midominio.com:8081
    at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:131) ~[?:?]
    ... 21 more
Caused by: java.nio.channels.ClosedChannelException
    ... 16 more

**Comment by sivasamyk** [comment]
Looks like there is some issue with SSL handshake. I have fixed the issues by explicitly specifying the SSL protocols to be used. Please use this update plugin and jar let me know if your issue is fixed.

Attached is the zip file. Please unzip to get the jar.

[graylog2-plugin-input-httpmonitor-1.0.3.jar.zip](https://github.com/sivasamyk/graylog2-plugin-input-httpmonitor/files/412589/graylog2-plugin-input-httpmonitor-1.0.3.jar.zip)

**Comment by sivasamyk** [comment]
Hi @elgersonloco
Did you get time to try out the above plugin jar with fix?

**Comment by danvey** [comment]
Hijacking this one, as no reply from user :-) I just installed the plugin, and I am also getting a SSL handshake issue.

Tried the .jar file you provided above, but now I am getting the following:
Request failed :java.net.ConnectException: handshake alert:  unrecognized_name

Any tips?

**Comment by sivasamyk** [comment]
@danvey This is due to wildcard / multi-domain SSL certificates when SNI is enabled in Java. There is a workaround for this issue. You can pass `-Djsse.enableSNIExtension=false` setting to graylog JVM to disable SNI at JVM level. Please be aware of security implications. The JVM settings can be changed in `graylog-server` file

**Comment by danvey** [comment]
@sivasamyk Thanks, this worked perfectly.
